# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = true

  config.vm.provision "shell", inline: <<-SHELL
    set -x
    	sudo yum update
        sudo yum install epel-release -y	
	sudo yum install net-tools ifconfig tcpdump -y
	sudo sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config	
  SHELL

  config.vm.define "vpnservertun", primary: true do |s|
    s.vm.hostname = 'vpnservertun'
    s.vm.network "private_network", ip: "192.168.15.12"
    s.vm.provision "shell", inline: <<-SHELL
    sudo ip tunnel add tun0 mode ipip remote 192.168.15.13 local 192.168.15.12 dev eth1
    sudo ip address add 10.0.0.12/24 dev tun0
    sudo ifconfig tun0 mtu 1492 up
    SHELL
  end

  config.vm.define "vpnclienttun" do |c|
    c.vm.hostname = 'vpnclienttun'
    c.vm.network "private_network", ip: "192.168.15.13"
    c.vm.provision "shell", inline: <<-SHELL
    sudo ip tunnel add tun0 mode ipip remote 192.168.15.12 local 192.168.15.13 dev eth1
    sudo ip address add 10.0.0.13/24 dev tun0
    sudo ifconfig tun0 mtu 1492 up
    SHELL
   end
  end
